// All site copy, EN + ES. Written in Eva's first-person voice; drafts for her to rewrite.
window.TSENOH_COPY = {
  en: {
    announce1: "Cut and sewn by hand in Cruïlles, Baix Empordà",
    announce2: "Free shipping in Spain from 150 €",
    announce3: "Natural fibres only. Nothing that the earth can't take back",
    bag: "Bag",
    navShop: "The shop", navOoak: "One of a kind", navSky: "Shop by the stars",
    navFibres: "Fibres", navEva: "Hello, I'm Eva", navLetters: "Letters",
    heroEyebrow: "Linen · wool · recovered fabrics",
    heroTag: "Textiles grown under the Moon and Stars",
    heroCta: "Come and see",
    heroGoods: "Good textile goods",
    heroTitle: "Textiles grown<br>under the <em>moon</em><br>&amp; stars!",
    heroCta2: "See the pieces",
    sticker: "made slowly ✦ worn for years",
    moonEyebrow: "Tonight over the studio",
    ribbon: "<span>100% natural</span><i>✦</i><span>made in Spain</span><i>✦</i><span>biodegradable</span><i>✦</i><span>oversized &amp; unisex</span><i>✦</i><span>only one of each</span><i>✦</i><span>100% natural</span><i>✦</i><span>made in Spain</span><i>✦</i><span>biodegradable</span><i>✦</i><span>oversized &amp; unisex</span><i>✦</i><span>only one of each</span><i>✦</i>",
    ooakTitle: "There is only <em>one</em>.<br>Then it's gone.",
    ooakLede: "Shirts cut from English shirting fabric that I rescued from Derby Gardeazabal, a Bilbao tailor that closed in 2022 after seventy years. Old handkerchiefs become pockets. No two are the same, and I won't make them again.",
    swipe: "swipe →",
    skyEyebrow: "Shop by the stars",
    skyTitle: "Every piece has<br>a <em>star</em> name",
    skyLede: "Sirius, Vega, Aries, Minerva… Touch a star to see who lives there.",
    skyCount: n => `${n} ${n === 1 ? "piece" : "pieces"} in this star`,
    shopTitle: "The <em>shop</em>",
    chipAll: "All", chipOoak: "One of a kind", chipLinen: "Linen", chipKnit: "Knitwear", chipAcc: "Accessories", chipAvail: "Available now",
    oneLeft: "1/1", soldOut: "Resting", add: "Add to bag", added: "In your bag ✦",
    notify: "Tell me when it's back", notified: "I'll write to you ✦",
    soldOutLine: "This one is resting until the next batch.",
    ooakLine: "There is only one in the whole world.",
    fibresEyebrow: "What it's made of",
    fibresTitle: "Fibres that <em>breathe</em>",
    f1t: "Linen", f1p: "EU-certified linen. Strong, cool, and it doesn't keep odours. It gets softer every summer you wear it.",
    f2t: "Merino & mohair", f2p: "Warm without weight, for the Empordà winters when the tramuntana blows.",
    f3t: "Recovered fabrics", f3p: "Antique shop finds and tailoring fabrics that I have kept with love for years. Old cloth, new life.",
    evaEyebrow: "Hello, I'm Eva",
    evaBig: "I believe that what we wear changes how we feel, at a very primal level.",
    evaP1: "After twenty years as a textile designer, I started Tsenoh! in 2020 as my own space to research, to play, and to look for a gentler way of making clothes.",
    evaP2: "Today I work from a small studio and shop in the countryside of Cruïlles. The landscape, the old crafts and the moon decide a lot of what happens here.",
    lettersEyebrow: "Letters from the studio",
    lettersTitle: "I write when<br>the <em>moon</em> changes",
    lettersLede: "Not when an algorithm asks. New pieces before anyone else, a fabric I found in some antique shop, what's blooming outside the door. Four times a month at most, often less.",
    lettersPlaceholder: "your email",
    lettersBtn: "Send me the moon",
    lettersDone: "Done. See you at the next full moon ✦",
    lettersSmall: "No spam, no countdowns. Leave whenever you want.",
    footMade: "Studio & shop in Cruïlles, Baix Empordà. Made in Spain, with natural fibres, in small batches.",
    footProto: "Proto 3.",
    bagTitle: "Your bag", subtotal: "Subtotal",
    checkout: "Checkout securely", checkoutNote: "You'll finish on the Tsenoh! Shopify checkout: cards, Apple Pay, Google Pay, Klarna.",
    bagEmpty: "Your bag is light as linen. For now.",
    shipLeft: n => `${n} € more and shipping in Spain is on me`,
    shipDone: "Shipping in Spain is on me ✦",
    remove: "remove",
    moonLines: [
      "New moon. A night for beginnings: sow something.",
      "The moon is growing. So is the new collection.",
      "First quarter. Half light, half dream.",
      "Almost full. Hang the linen out tonight.",
      "Full moon. Wear the thing you love the most.",
      "The moon is getting smaller. Time to keep, mend, and rest.",
      "Last quarter. Clear the table, clear the head.",
      "A thin moon. Quiet studio days.",
    ],
    moonNames: ["New moon", "Waxing crescent", "First quarter", "Waxing gibbous", "Full moon", "Waning gibbous", "Last quarter", "Waning crescent"],
    lit: "lit",
    rain: "You found the pink rain ✦",
  },
  es: {
    announce1: "Cortado y cosido a mano en Cruïlles, Baix Empordà",
    announce2: "Envío gratis en España desde 150 €",
    announce3: "Solo fibras naturales. Nada que la tierra no pueda recuperar",
    bag: "Bolsa",
    navShop: "La tienda", navOoak: "Piezas únicas", navSky: "Compra por estrellas",
    navFibres: "Fibras", navEva: "Hola, soy Eva", navLetters: "Cartas",
    heroEyebrow: "Lino · lana · tejidos recuperados",
    heroTag: "Tejidos que crecen bajo la Luna y las Estrellas",
    heroCta: "Ven a ver",
    heroGoods: "Good textile goods",
    heroTitle: "Tejidos que crecen<br>bajo la <em>luna</em><br>y las estrellas!",
    heroCta2: "Ver las piezas",
    sticker: "hecho despacio ✦ para llevar años",
    moonEyebrow: "Esta noche sobre el taller",
    ribbon: "<span>100% natural</span><i>✦</i><span>hecho en España</span><i>✦</i><span>biodegradable</span><i>✦</i><span>oversized y unisex</span><i>✦</i><span>solo una de cada</span><i>✦</i><span>100% natural</span><i>✦</i><span>hecho en España</span><i>✦</i><span>biodegradable</span><i>✦</i><span>oversized y unisex</span><i>✦</i><span>solo una de cada</span><i>✦</i>",
    ooakTitle: "Solo existe <em>una</em>.<br>Y luego se va.",
    ooakLede: "Camisas cortadas en tejido inglés de camisería que rescaté de Derby Gardeazabal, una sastrería de Bilbao que cerró en 2022 después de setenta años. Pañuelos antiguos que se convierten en bolsillos. No hay dos iguales, y no las volveré a hacer.",
    swipe: "desliza →",
    skyEyebrow: "Compra por estrellas",
    skyTitle: "Cada pieza tiene<br>nombre de <em>estrella</em>",
    skyLede: "Sirius, Vega, Aries, Minerva… Toca una estrella y mira quién vive allí.",
    skyCount: n => `${n} ${n === 1 ? "pieza" : "piezas"} en esta estrella`,
    shopTitle: "La <em>tienda</em>",
    chipAll: "Todo", chipOoak: "Piezas únicas", chipLinen: "Lino", chipKnit: "Punto", chipAcc: "Accesorios", chipAvail: "Disponible",
    oneLeft: "1/1", soldOut: "Descansando", add: "Añadir a la bolsa", added: "En tu bolsa ✦",
    notify: "Avísame cuando vuelva", notified: "Te escribiré ✦",
    soldOutLine: "Esta pieza descansa hasta la próxima tanda.",
    ooakLine: "Solo existe una en todo el mundo.",
    fibresEyebrow: "De qué está hecho",
    fibresTitle: "Fibras que <em>respiran</em>",
    f1t: "Lino", f1p: "Lino con certificado europeo. Resistente, fresco y no retiene olores. Cada verano que lo llevas es más suave.",
    f2t: "Merino y mohair", f2p: "Abriga sin pesar, para los inviernos del Empordà cuando sopla la tramontana.",
    f3t: "Tejidos recuperados", f3p: "Hallazgos de anticuarios y telas de sastrería que he guardado con cariño durante años. Tela vieja, vida nueva.",
    evaEyebrow: "Hola, soy Eva",
    evaBig: "Creo que lo que llevamos puesto cambia cómo nos sentimos, a un nivel muy primario.",
    evaP1: "Después de veinte años como diseñadora textil, empecé Tsenoh! en 2020 como mi propio espacio para investigar, para jugar y para buscar una forma más amable de hacer ropa.",
    evaP2: "Hoy trabajo desde un pequeño taller y tienda en el campo de Cruïlles. El paisaje, los oficios antiguos y la luna deciden mucho de lo que pasa aquí.",
    lettersEyebrow: "Cartas desde el taller",
    lettersTitle: "Escribo cuando<br>cambia la <em>luna</em>",
    lettersLede: "No cuando lo pide un algoritmo. Piezas nuevas antes que nadie, una tela que encontré en algún anticuario, lo que florece delante de la puerta. Cuatro veces al mes como mucho, a menudo menos.",
    lettersPlaceholder: "tu email",
    lettersBtn: "Envíame la luna",
    lettersDone: "Hecho. Nos vemos en la próxima luna llena ✦",
    lettersSmall: "Sin spam, sin cuentas atrás. Te vas cuando quieras.",
    footMade: "Taller y tienda en Cruïlles, Baix Empordà. Hecho en España, con fibras naturales, en tandas pequeñas.",
    footProto: "Proto 3.",
    bagTitle: "Tu bolsa", subtotal: "Subtotal",
    checkout: "Pagar con seguridad", checkoutNote: "Terminas en el checkout de Shopify de Tsenoh!: tarjeta, Apple Pay, Google Pay, Klarna.",
    bagEmpty: "Tu bolsa está ligera como el lino. De momento.",
    shipLeft: n => `Te faltan ${n} € y el envío en España corre de mi cuenta`,
    shipDone: "El envío en España corre de mi cuenta ✦",
    remove: "quitar",
    moonLines: [
      "Luna nueva. Una noche para empezar: siembra algo.",
      "La luna crece. La nueva colección también.",
      "Cuarto creciente. Media luz, medio sueño.",
      "Casi llena. Esta noche tiende el lino fuera.",
      "Luna llena. Ponte lo que más quieres.",
      "La luna mengua. Tiempo de guardar, remendar y descansar.",
      "Cuarto menguante. Limpia la mesa, limpia la cabeza.",
      "Una luna fina. Días tranquilos en el taller.",
    ],
    moonNames: ["Luna nueva", "Luna creciente", "Cuarto creciente", "Gibosa creciente", "Luna llena", "Gibosa menguante", "Cuarto menguante", "Luna menguante"],
    lit: "iluminada",
    rain: "Has encontrado la lluvia rosa ✦",
  },
};
