"""Snapshot the public Shopify catalog of tsenoh.com into data.js (EN + ES)."""
import json, re, html, urllib.request

BASE = "https://tsenoh.com"
COLLECTIONS = ["one-of-a-kind", "linen", "knitwear", "accessories", "twin-sets", "dresses"]


def get(path):
    req = urllib.request.Request(BASE + path, headers={"User-Agent": "Mozilla/5.0"})
    return json.load(urllib.request.urlopen(req))


def paragraphs(body):
    body = re.sub(r"<br\s*/?>", "\n", body or "")
    body = re.sub(r"</(p|div|li|h\d)>", "\n", body)
    text = html.unescape(re.sub(r"<[^>]+>", "", body))
    return [re.sub(r"\s+", " ", l).strip() for l in text.split("\n") if l.strip()]


en = get("/products.json?limit=250")["products"]
es = {p["id"]: p for p in get("/es/products.json?limit=250")["products"]}
membership = {c: {p["handle"] for p in get(f"/collections/{c}/products.json?limit=250")["products"]} for c in COLLECTIONS}

out = []
for p in en:
    v = p["variants"][0]
    e = es.get(p["id"], p)
    lines_en, lines_es = paragraphs(p["body_html"]), paragraphs(e["body_html"])
    out.append({
        "handle": p["handle"],
        "title": p["title"].title().replace('"', ""),
        "variant": v["id"],
        "price": float(v["price"]),
        "available": v["available"],
        "type": p["product_type"],
        "ooak": '"One of a Kind"' in p["tags"],
        "collections": [c for c in COLLECTIONS if p["handle"] in membership[c]],
        "images": [i["src"] for i in p["images"][:6]],
        "ratio": round(p["images"][0]["height"] / p["images"][0]["width"], 3) if p["images"] else 1.25,
        "en": {"sub": lines_en[0] if lines_en else "", "body": lines_en[1:14]},
        "es": {"sub": lines_es[0] if lines_es else "", "body": lines_es[1:14]},
    })

with open("data.js", "w") as f:
    f.write("// Generated by tools/build-data.py from the public tsenoh.com catalog.\n")
    f.write("window.TSENOH_PRODUCTS = " + json.dumps(out, ensure_ascii=False) + ";\n")
print(len(out), "products;", sum(p["available"] for p in out), "available")
